/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SessionSessionKeyImport } from './routes/session/$sessionKey'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SessionSessionKeyRoute = SessionSessionKeyImport.update({
  id: '/session/$sessionKey',
  path: '/session/$sessionKey',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/session/$sessionKey': {
      id: '/session/$sessionKey'
      path: '/session/$sessionKey'
      fullPath: '/session/$sessionKey'
      preLoaderRoute: typeof SessionSessionKeyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/session/$sessionKey': typeof SessionSessionKeyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/session/$sessionKey': typeof SessionSessionKeyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/session/$sessionKey': typeof SessionSessionKeyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/session/$sessionKey'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/session/$sessionKey'
  id: '__root__' | '/' | '/session/$sessionKey'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessionSessionKeyRoute: typeof SessionSessionKeyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionSessionKeyRoute: SessionSessionKeyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/session/$sessionKey"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/session/$sessionKey": {
      "filePath": "session/$sessionKey.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
